# Generated by Django 5.1.6 on 2025-02-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.TextField()),
                ("file_type", models.CharField(blank=True, max_length=10, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_data",
            },
        ),
        migrations.CreateModel(
            name="ProcessedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_json", models.JSONField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_ingestion.uploadeddata",
                    ),
                ),
            ],
            options={
                "db_table": "processed_data",
            },
        ),
    ]
