# Generated by Django 5.1.6 on 2025-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddata",
            name="file_path",
        ),
        migrations.AddField(
            model_name="uploadeddata",
            name="file",
            field=models.FileField(default="default_file.txt", upload_to="uploads/"),
        ),
    ]
